namespace BalticAmadeus.FluentMdx.Lexer
{
    internal enum TokenType
    {
        LastToken,
        Select,
        Non,
        Empty,
        From,
        On,
        MemberSeparator,
        LeftCurlyBracket,
        RightCurlyBracket,
        IdentifierExpression,
        AxisName,
        LeftRoundBracket,
        RightRoundBracket,
        RangeSeparator,
        Where,
        ValueSeparator,
        LeftSquareBracket,
        RightSquareBracket,
        IdentifierSeparator,
        DimensionProperty,
        Dimension,
        Properties,
        NumberExpression,
        MathsOperator,
        DateExpression,
        NotOperator,
        LogicsOperator,
        LogicalExpression,
        MultiplicationOperator
    }
}